### ISSUE TITLE
Theme Frontend

### ISSUE THREAD

**Issue by kaspar-allenbach** [httpster/Ace-Freely#2]
Hi.

How do I pass along the code highlighting theme to the front-end?

`<pre>{{ entry.cellCode | raw }}</pre>`

This prints the code correctly. But there isn't any Styling applied. Whats the catch here?

**Comment by richhayler** [comment]
Here's a great post that explains one way to tackle this: https://www.mikestreety.co.uk/blog/making-craft-cms-work-with-prism-js-using-pre-and-code-blocks
